language: java
jdk: oraclejdk8
install: ./gradlew clean build
after_success: ./gradlew jacocoTestReport coveralls

branches:
  only:
    - master
    - develop

env:
  global:
    - CI_NAME=travis-ci
